---
- name: "update apt packages."
  become: true
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: true
  apt:
    upgrade: yes

- name: "install node and npm"
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  command: npm install pm2 -g

- name: "create directory"
  file:
    path: ~/web
    mode: 0755
    state: directory

- name: "copy files over to instance"
  copy:
    src: index.js
    dest: ~/web/index.js
    backup: yes

- name: "Start Node app with pm2"
  command: pm2 start ~/web/index.js -f